### ISSUE TITLE
[Question] Where to find PROTONMAIL_EXTRA_2FA?

### ISSUE THREAD

**Issue by Legym** [sdelafond/docker-protonmail-bridge#3]
This code is a life saver! I have a Wordpress site setup, but emails do not work because my domain uses Protonmail. 

The only env variable I didn't know where to find was `PROTONMAIL_EXTRA_2FA`. Where can I find this in protonmail? 

Thank you!

**Comment by sdelafond** [comment]
If you've enabled 2-factor authentication in ProtonMail, then it's the 6 digit code returned by your auth app.

**Comment by Legym** [comment]
That makes sense. Thank you!
