### ISSUE TITLE
TLS handshake error with Mattermost

### ISSUE THREAD

**Issue by Guiraud** [sdelafond/docker-protonmail-bridge#4]
Hi, 
I've installed the Docker container but i get this error : 
`
smtp/server 2021/04/10 14:17:03 TLS handshake error for 127.0.0.1:47610: remote error: tls: bad certificate
`
Mattermost conf :
Any help ? 
![Capture d’écran 2021-04-10 à 16 26 54](https://user-images.githubusercontent.com/6224365/114273257-a0595100-9a19-11eb-9747-3c436b6e99b6.png)

**Comment by sdelafond** [comment]
The bridge is using a self-signed cert, hence the README section describing how to extract the fingerprint so you can manuallly trust it in whatever client you choose. If your client doesn't offer that ability, then you're out of luck.
