### ISSUE TITLE
docker allow for multiple logins

### ISSUE THREAD

**Issue by ipflowss** [sdelafond/docker-protonmail-bridge#5]
Hi there - is it easy to configure the docker to access 2  or more protonmail accounts?  do I need a docker running for each account?

**Comment by DittmarSteiner** [comment]
Interesting question! 
I would recommend one Docker image and multiple containers. This is the very idea of Docker.
I often use Docker Compose and a `.env` file next to `docker-compose.yml` to pass env values.

What do you think about this?

**Comment by sdelafond** [comment]
That's why I took the time to variabilize all the configuration in an env file for this docker-compose setup.

**Comment by sdelafond** [comment]
Closing this, as the solution was described above.
