### ISSUE TITLE
tls: unknown certificate authority

### ISSUE THREAD

**Issue by ipflowss** [sdelafond/docker-protonmail-bridge#6]
Aloha,

I am trying to get freescout integrated with the protonmail bridge.  I
am getting the following errors.  is the cert you are send to protonmail
a legitimately signed cert from a trusted CA?

:::error appearing on the freescout webUI:::
stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL
Error messages: error:1416F086:SSL
routines:tls_process_server_certificate:certificate verify failed

:::from the docker log output:::
smtp/server 2021/06/20 12:44:58 TLS handshake error for 127.0.0.1:35502:
remote error: tls: unknown certificate authority

Cheers

**Comment by sdelafond** [comment]
The bridge is using a self-signed cert, hence the README section describing how to extract the fingerprint so you can manuallly trust it in whatever client you choose. If your client doesn't offer that ability, then you're out of luck.

Duplicates #4.

**Comment by ipflowss** [comment]
Thank you
