### ISSUE TITLE
Can't login using 1.8.3

### ISSUE THREAD

**Issue by sdelafond** [sdelafond/docker-protonmail-bridge#7]
I tried to migrate to the latest upstream version this morning, but unfortunately something seems to be broken with non-interactive login in 1.8.3. Here's my email to bridge@:

```
Up to 1.5.4, I was able to login in a fully non-interactive way using:

  echo -e "login\n${PROTONMAIL_LOGIN}\n${PROTONMAIL_PASSWORD}\n${PROTONMAIL_EXTRA_2FA}" | protonmail-bridge --cli

With 1.8.3, this does not appear to work anymore, as I get the following
error:

  ERRO[Jun 21 06:03:17.165] Could not unmarshal secret error="backend/credentials: malformed secret: malformed credent\
ials" pkg=credentials user="<some_base64_string"

Could you please describe how to perform a non-interactive login with
1.8.x? If you'd rather discuss this in a new issue on the corresponding
github project, please let me know.
```

**Comment by ipflowss** [comment]
Okay - now I want to install version 1.5.4 deb file.  How can I get the 1.5.4 deb file?  Both of the following commands leads to 404s
```
wget https://protonmail.com/download/bridge/protonmail-bridge_1.5.4-1_amd64.deb
wget https://protonmail.com/download/bridge/protonmail-bridge_1.5.4_amd64.deb
```

**Comment by sdelafond** [comment]
@ipflowss well I'm not going to be able to do much about that, now will I? How about you reach out to ProtonMail, or do a bit of web searching?

Also, this issue is for 1.8.3 support, could you please not derail it?

**Comment by sdelafond** [comment]
1.8.10-1 fixes this, at least in a bullseye-based setup.

**Comment by ipflowss** [comment]
What do you mean by bullseye based set up?

**Comment by sdelafond** [comment]
> What do you mean by bullseye based set up?

27f283572ecdc78c24eebde767cab49a63d6c58d
